name: Node.js CI Project
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to the Dockerhub
        uses: docker/login-action@v1
        with:
          username: aataafridi3
          password: Devops2024@
          
      - name: docker build 
        uses: docker/build-push-action@v2
        with:
          content: ./
          file: ./Dockerfile
          push: true
          tags: aataafridi3/nodeimage:v1

      - name: deploy the the app
        run: kubectl apply -f $GITHUB_WORKSPACE/deployment.yml
      
