name: Node.js CI Project
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: docker build 
        uses: docker/build-push-action@v2
        with:
          content: ./
          file: ./Dockerfile
      
